spring:
  datasource:
    url: jdbc:mysql://localhost:3306/verification_server
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: outlook.office365.com
    port: 587
    username:
    password:
    properties:
      mail.smtp.starttls.enable: true

sms:
  enabled: true
  secret-id: secret-id
  secret-key: secret-key
  template-id: template-id
  sdk-app-id: sdk-app-id
  sign-name: sign-name

springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan:
        - com.prprv.verification
